///////////////////////////////////////////////////////////
//  AddTrening.cs
//  Implementation of the Class AddTrening
//  Generated by Enterprise Architect
//  Created on:      11-Sep-2020 10:59:48 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AddTrening : ICommandUR {

	public Trening trening;

	public AddTrening(){

	}

	~AddTrening(){

	}

	/// 
	/// <param name="trening"></param>
	public AddTrening(Trening trening){
		this.trening = trening;
	}

	public string ExecuteA(int id, IDBService service)
	{
		return service.AddTreningAdmin(id, trening);
	}

	public string UnExecuteA(Osoba osoba, IDBService service)
	{
		return service.DeleteTrening(osoba, trening);
	}

	/// 
	/// <param name="id"></param>
	/// <param name="service"></param>
	public string ExecuteV(int id, IDBService service){

		return service.AddTreningVezbac(id, trening);
	}

	/// 
	/// <param name="osoba"></param>
	/// <param name="service"></param>
	public string UnExecuteV(Osoba osoba, IDBService service){

		return service.DeleteTrening(osoba, trening);
	}

}//end AddTrening