///////////////////////////////////////////////////////////
//  AddTrening.cs
//  Implementation of the Class AddTrening
//  Generated by Enterprise Architect
//  Created on:      11-Sep-2020 10:59:48 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AddTrening : ICommand {

	public Trening trening;

	public AddTrening(){

	}

	~AddTrening(){

	}

	/// 
	/// <param name="trening"></param>
	public AddTrening(Trening trening){

	}

	public void Execute(){

	}

	public void UnExecute(){

	}

}//end AddTrening