///////////////////////////////////////////////////////////
//  Admin.cs
//  Implementation of the Class Admin
//  Generated by Enterprise Architect
//  Created on:      11-Sep-2020 6:25:09 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

public class Admin : Osoba {
	public List<Trening> treninzi { get; set; }


	public Admin(){

	}

	~Admin(){

	}

	public override string FullName{
		get;
		set;
	}

	public override int ID{
		get;
		set;
	}

	public override string Password{
		get;
		set;
	}

	public override int Role{
		get;
		set;
	}

	public override string ToString(){

		return "";
	}

	public override string Username{
		get;
		set;
	}

}//end Admin