///////////////////////////////////////////////////////////
//  Admin.cs
//  Implementation of the Class Admin
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:32 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Admin : Osoba {

	public Admin(){

	}

	~Admin(){

	}

	public override int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

	public override string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public override int Role{
		get{
			return role;
		}
		set{
			role = value;
		}
	}

	public override string Surname{
		get{
			return surname;
		}
		set{
			surname = value;
		}
	}

	public override string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

}//end Admin