///////////////////////////////////////////////////////////
//  Contract.cs
//  Implementation of the Class Contract
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2020 7:44:02 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Contract : IContract {

	private DBService dbService = new DBService();;
	private Proxy proxy = new Proxy(dbService);;
	public LogInOut LogInOut;
	public CRUDUser m_CRUDUser;
	public RefreshPage m_RefreshPage;
	public CRUDTrening m_CRUDTrening;

	public Contract(){

	}

	~Contract(){

	}

	/// 
	/// <param name="admin"></param>
	public string CreateAdmin(Admin admin){

		return "";
	}

	/// 
	/// <param name="vezbac"></param>
	public string CreateVezbac(Vezbac vezbac){

		return "";
	}

	/// 
	/// <param name="user"></param>
	public Admin LogInAdmin(LoginUser user){

		return null;
	}

	/// 
	/// <param name="user"></param>
	public Vezbac LogInVezbac(LoginUser user){

		return null;
	}

	/// 
	/// <param name="osoba"></param>
	public void LogOut(Osoba osoba){

	}

}//end Contract