///////////////////////////////////////////////////////////
//  CRUDTrening.cs
//  Implementation of the Class CRUDTrening
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2020 6:58:25 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CRUDTrening {

	public UndoRedo undoRedo;

	public CRUDTrening(){

	}

	~CRUDTrening(){

	}

}//end CRUDTrening