///////////////////////////////////////////////////////////
//  CRUDUser.cs
//  Implementation of the Class CRUDUser
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2020 7:47:23 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CRUDUser {

	public CRUDUser(){

	}

	~CRUDUser(){

	}

	/// 
	/// <param name="admin"></param>
	/// <param name="service"></param>
	public string CreateAdmin(Admin admin, IDBService service){

		return service.AddAdmin(admin);
	}

	/// 
	/// <param name="vezbac"></param>
	/// <param name="service"></param>
	public string CreateVezbac(Vezbac vezbac, IDBService service){

		return service.AddVezbav(vezbac);
	}

	/// 
	/// <param name="service"></param>
	public List<Admin> GetAllAdmins(IDBService service){

		return service.GetAllAdmins();
	}

	/// 
	/// <param name="service"></param>
	public List<Vezbac> GetAllVezbace(IDBService service){

		return service.GetAllVezbace();
	}

	/// 
	/// <param name="admin"></param>
	/// <param name="service"></param>
	public string DeleteAdmin(Admin admin, IDBService service){

		return service.DeleteAdmin(admin);
	}

	/// 
	/// <param name="vezbac"></param>
	/// <param name="service"></param>
	public string DeleteVezbac(Vezbac vezbac, IDBService service){

		return service.DeleteVezbac(vezbac);
	}

}//end CRUDUser