///////////////////////////////////////////////////////////
//  CRUDUser.cs
//  Implementation of the Class CRUDUser
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2020 7:47:23 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CRUDUser {

	public CRUDUser(){

	}

	~CRUDUser(){

	}

	/// 
	/// <param name="admin"></param>
	/// <param name="service"></param>
	public string CreateAdmin(Admin admin, IDBService service){

		return service.AddAdmin(admin);
	}

	/// 
	/// <param name="vezbac"></param>
	/// <param name="service"></param>
	public string CreateVezbac(Vezbac vezbac, IDBService service){

		return service.AddVezbav(vezbac);
	}

	/// 
	/// <param name="service"></param>
	public List<Admin> GetAllAdmins(IDBService service){

		return service.GetAllAdmins();
	}

	/// 
	/// <param name="service"></param>
	public List<Vezbac> GetAllVezbace(IDBService service){

		return service.GetAllVezbace();
	}

	/// 
	/// <param name="admin"></param>
	/// <param name="service"></param>
	public string DeleteAdmin(Admin admin, IDBService service){

		return service.DeleteAdmin(admin);
	}

	/// 
	/// <param name="vezbac"></param>
	/// <param name="service"></param>
	public string DeleteVezbac(Vezbac vezbac, IDBService service){

		return service.DeleteVezbac(vezbac);
	}

	/// 
	/// <param name="admin"></param>
	/// <param name="service"></param>
	public string ChangeAdmin(Admin admin, IDBService service){

		return service.ChangeAdmin(admin);
	}

	/// 
	/// <param name="vezbac"></param>
	/// <param name="service"></param>
	public string ChangeVezbac(Vezbac vezbac, IDBService service){

		return service.ChangeVezbac(vezbac);
	}

	/// 
	/// <param name="trener"></param>
	public string CreateTrener(Trener trener, IDBService service){

		return service.CreateTrener(trener);
	}

	/// 
	/// <param name="trener"></param>
	/// <param name="service"></param>
	public string ChangeTrener(Trener trener, IDBService service){

		return service.ChangeTrener(trener);
	}

	/// 
	/// <param name="id"></param>
	/// <param name="service"></param>
	public string DeleteTrener(int id, IDBService service){

		return service.DeleteTrener(id);
	}

	/// 
	/// <param name="osoba"></param>
	/// <param name="service"></param>
	public string ChangeUser(object osoba, IDBService service){

		return service.ChangeUser(osoba);
	}

	/// 
	/// <param name="type"></param>
	/// <param name="input"></param>
	public string SearchUser(string type, string input, IDBService service)
	{
		return service.SearchUser(type, input);
	}

}//end CRUDUser