///////////////////////////////////////////////////////////
//  DeleteTrening.cs
//  Implementation of the Class DeleteTrening
//  Generated by Enterprise Architect
//  Created on:      23-Sep-2020 7:59:02 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DeleteTrening : ICommandUR {

	public Trening trening;

	public DeleteTrening()
	{
		
	}

	~DeleteTrening(){

	}

	/// 
	/// <param name="trening"></param>
	public DeleteTrening(Trening trening){
		this.trening = trening;
	}

	public string ExecuteA(int id, IDBService service)
	{
		var osoba = new Admin();
		osoba.ID = id;
		osoba.Role = 0;
		return service.DeleteTrening(osoba, trening);
	}

	public string UnExecuteA(int id, IDBService service)
	{
		trening.ID = 0;
		return service.AddTreningAdmin(id, trening);
	}

	/// 
	/// <param name="id"></param>
	/// <param name="service"></param>
	public string ExecuteV(int id, IDBService service){

		var osoba = new Vezbac();
		osoba.ID = id;
		osoba.Role = 1;
		return service.DeleteTrening(osoba, trening);
	}

	/// 
	/// <param name="osoba"></param>
	/// <param name="service"></param>
	public string UnExecuteV(int id, IDBService service){

		trening.ID = 0;
		return service.AddTreningVezbac(id, trening);
	}
}//end DeleteTrening