///////////////////////////////////////////////////////////
//  DeleteTrening.cs
//  Implementation of the Class DeleteTrening
//  Generated by Enterprise Architect
//  Created on:      23-Sep-2020 7:59:02 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DeleteTrening : ICommandUR {

	public Trening trening;

	public DeleteTrening()
	{
		
	}

	~DeleteTrening(){

	}

	/// 
	/// <param name="trening"></param>
	public DeleteTrening(Trening trening){
		this.trening = trening;
	}

	public void Execute(){

	}

	public void UnExecute(){

	}

}//end DeleteTrening