///////////////////////////////////////////////////////////
//  ICommand.cs
//  Implementation of the Interface ICommand
//  Generated by Enterprise Architect
//  Created on:      23-Sep-2020 7:59:03 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICommandUR  {

	void Execute();

	void UnExecute();
}//end ICommandUR//end ICommand