///////////////////////////////////////////////////////////
//  ICommand.cs
//  Implementation of the Interface ICommand
//  Generated by Enterprise Architect
//  Created on:      23-Sep-2020 7:59:03 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICommandUR  {

	string ExecuteA(int id, IDBService service);

	string UnExecuteA(int id, IDBService service);

	string ExecuteV(int id, IDBService service);

	string UnExecuteV(int id, IDBService service);
}//end ICommandUR//end ICommand