///////////////////////////////////////////////////////////
//  ICommand.cs
//  Implementation of the Interface ICommandUR
//  Generated by Enterprise Architect
//  Created on:      26-Sep-2020 4:17:26 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICommandUR   {

	/// 
	/// <param name="id"></param>
	/// <param name="service"></param>
	string ExecuteA(int id, IDBService service);

	/// 
	/// <param name="id"></param>
	/// <param name="service"></param>
	string ExecuteV(int id, IDBService service);

	/// 
	/// <param name="osoba"></param>
	/// <param name="service"></param>
	string UnExecuteA(Osoba osoba, IDBService service);

	/// 
	/// <param name="osoba"></param>
	/// <param name="service"></param>
	string UnExecuteV(Osoba osoba, IDBService service);
}//end ICommandUR