///////////////////////////////////////////////////////////
//  IContract.cs
//  Implementation of the Interface IContract
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2020 7:44:04 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IContract         {

	/// 
	/// <param name="admin"></param>
	string CreateAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string CreateVezbac(Vezbac vezbac);

	/// 
	/// <param name="user"></param>
	Admin LogInAdmin(LoginUser user);

	/// 
	/// <param name="user"></param>
	Vezbac LogInVezbac(LoginUser user);

	/// 
	/// <param name="osoba"></param>
	void LogOut(Osoba osoba);

	List<Admin> GetAllAdmins();

	List<Vezbac> GetAllVezbace();

	/// 
	/// <param name="username"></param>
	void LogOut(string username);

	/// 
	/// <param name="admin"></param>
	string DeleteAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string DeleteVezbac(Vezbac vezbac);

	/// 
	/// <param name="admin"></param>
	string ChangeAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string ChangeVezbac(Vezbac vezbac);

	List<Trener> GetTrenere();

	/// 
	/// <param name="osoba"></param>
	LIst<Trening> GetTreninge(Osoba osoba);

	/// 
	/// <param name="adminId"></param>
	/// <param name="trening"></param>
	string AddTreningAdmin(int adminId, Trening trening);

	/// 
	/// <param name="vezbacId"></param>
	/// <param name="trening"></param>
	string AddTreningVezbac(int vezbacId, Trening trening);

	/// 
	/// <param name="osoba"></param>
	/// <param name="trening"></param>
	string DeleteTrening(Osoba osoba, Trening trening);

	/// 
	/// <param name="admin"></param>
	LIst<Trening> GetTreninge(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	List<Trening> GetTreninge(Vezbac vezbac);
}//end IContract