///////////////////////////////////////////////////////////
//  IDBService.cs
//  Implementation of the Interface IDBService
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 6:28:48 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IDBService           {

	/// 
	/// <param name="loginUser"></param>
	Admin FindAdmin(LoginUser loginUser);

	/// 
	/// <param name="loginUser"></param>
	Vezbac FindVezbac(LoginUser loginUser);

	/// 
	/// <param name="osoba"></param>
	void LogOut(string username);

	/// 
	/// <param name="admin"></param>
	string AddAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string AddVezbav(Vezbac vezbac);

	List<Admin> GetAllAdmins();

	List<Vezbac> GetAllVezbace();

	/// 
	/// <param name="admin"></param>
	string DeleteAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string DeleteVezbac(Vezbac vezbac);

	/// 
	/// <param name="admin"></param>
	string ChangeAdmin(Admin admin);

	/// 
	/// <param name="vezbac"></param>
	string ChangeVezbac(Vezbac vezbac);

	/// 
	/// <param name="vezbac"></param>
	string AddTreningVezbac(Vezbac vezbac);

	/// 
	/// <param name="trening"></param>
	string DeleteTrenin(Trening trening);

	/// 
	/// <param name="adminId"></param>
	/// <param name="trening"></param>
	string AddTreningAdmin(int adminId, Trening trening);

	List<Trener> GetTrenere();
}//end IDBService