///////////////////////////////////////////////////////////
//  LoginUser.cs
//  Implementation of the Class LoginUser
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LoginUser {
	private string password;
	private string username;


	public LoginUser(){

	}

	~LoginUser(){

	}

	/// 
	/// <param name="username"></param>
	/// <param name="password"></param>
	public LoginUser(string username, string password){

	}

	public string Password{
		get{
			return password;
		}
		set{
			password = value;
		}
	}

	public string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}
}//end LoginUser