///////////////////////////////////////////////////////////
//  LogInOut.cs
//  Implementation of the Class LogInOut
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:26:10 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LogInOut {

	public LogInOut(){

	}

	~LogInOut(){

	}

	/// 
	/// <param name="loginUser"></param>
	/// <param name="service"></param>
	public Admin LoginAdmin(LoginUser loginUser, IDBService service){

		return service.FindAdmin(loginUser);
	}

	/// 
	/// <param name="loginUser"></param>
	/// <param name="service"></param>
	public Vezbac LoginVezbac(LoginUser loginUser, IDBService service){

		return service.FindVezbac(loginUser);
	}

	/// 
	/// <param name="osoba"></param>
	public void Logout(string username, IDBService service)
	{
		service.LogOut(username);
	}

}//end LogInOut