///////////////////////////////////////////////////////////
//  LoginUser.cs
//  Implementation of the Class LoginUser
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LoginUser : Osoba_abs {

	public LoginUser(){

	}

	~LoginUser(){

	}

	/// 
	/// <param name="username"></param>
	/// <param name="password"></param>
	public LoginUser(string username, string password){

	}

	public override string Password{
		get{
			return password;
		}
		set{
			password = value;
		}
	}

	public override string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

	public override int Id {
		get
		{
			return id;
		}
		set
		{
			id = value;
		}
	}
	public override int Role {
		get
		{
			return role;
		}
		set
		{
			role = value;
		}
	}
}//end LoginUser