///////////////////////////////////////////////////////////
//  Osoba.cs
//  Implementation of the Class Osoba
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Osoba : Osoba_abs {

	protected string name;
	protected string surname;

	public Osoba(){

	}

	~Osoba(){

	}

	public override int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

	public virtual string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public override string Password{
		get{
			return password;
		}
		set{
			password = value;
		}
	}

	public override int Role{
		get{
			return role;
		}
		set{
			role = value;
		}
	}

	public virtual string Surname{
		get{
			return surname;
		}
		set{
			surname = value;
		}
	}

	public override string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

}//end Osoba

public abstract class Osoba_abs {

	protected int id;
	protected string password;
	protected int role;
	protected string username;

	public Osoba_abs(){

	}

	~Osoba_abs(){

	}

	public abstract int Id{
		get;
		set;
	}

	public abstract string Password{
		get;
		set;
	}

	public abstract int Role{
		get;
		set;
	}

	public abstract string Username{
		get;
		set;
	}

}//end Osoba_abs