///////////////////////////////////////////////////////////
//  Osoba.cs
//  Implementation of the Class Osoba
//  Generated by Enterprise Architect
//  Created on:      11-Sep-2020 6:25:09 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

public abstract class Osoba {

	public Osoba(){

	}

	~Osoba(){

	}

	public abstract string FullName{
		get;
		set;
	}

	[Key]
	public abstract int ID{
		get;
		set;
	}

	public abstract string Password{
		get;
		set;
	}

	public abstract int Role{
		get;
		set;
	}

	public abstract string ToString();

	public abstract string Username{
		get;
		set;
	}

}//end Osoba