///////////////////////////////////////////////////////////
//  Osoba.cs
//  Implementation of the Class Osoba
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Osoba {

	protected string name;
	protected string surname;
	protected int id;
	protected string password;
	protected int role;
	protected string username;

	public Osoba(){

	}

	~Osoba(){

	}

	protected abstract int Id{
		get;
		set;
	}

	protected abstract string Name{
		get;
		set;
	}

	protected abstract string Password{
		get;
		set;
	}

	protected abstract int Role{
		get;
		set;
	}

	protected abstract string Surname{
		get;
		set;
	}

	protected abstract string Username{
		get;
		set;
	}

	public override string  ToString(){

		return $"{Name} {Surname} [{Username}-{Role}]";
	}

}//end Osoba
