///////////////////////////////////////////////////////////
//  Trener.cs
//  Implementation of the Class Trener
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: tanja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Trener : Osoba {

	public List<Trening> trening;

	public Trener(){

	}

	~Trener(){

	}

	public override int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

	public override string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public override string Surname{
		get{
			return surname;
		}
		set{
			surname = value;
		}
	}

}//end Trener