///////////////////////////////////////////////////////////
//  Trening.cs
//  Implementation of the Class Trening
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: tanja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Trening {

	private DateTime termin;
	public Trener treneri;

	public Trening(){

	}

	~Trening(){

	}

	public DateTime Termin{
		get{
			return termin;
		}
		set{
			termin = value;
		}
	}

}//end Trening