///////////////////////////////////////////////////////////
//  UndoRedo.cs
//  Implementation of the Class UndoRedo
//  Generated by Enterprise Architect
//  Created on:      23-Sep-2020 7:57:59 PM
//  Original author: andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class UndoRedo {

	private Stack<ICommandUR> _Redocommands = new Stack<ICommandUR>();
	private Stack<ICommandUR> _Undocommands = new Stack<ICommandUR>();

	private int id { get; set; }
	private int role { get; set; }
	private IDBService service { get; set; }

	public UndoRedo(){
	}

	~UndoRedo(){

	}

	/// 
	/// <param name="trening"></param>
	public void InsertInUnDoRedoForAdd(int id, int role, IDBService service, Trening trening, out string message){

		message = "";
		ICommandUR commandUR = new AddTrening(trening);

		if (role == 0)
			message = commandUR.ExecuteA(id, service);
		else
			message = commandUR.ExecuteV(id, service);

		this.id = id;
		this.service = service;
		this.role = role;

		_Undocommands.Push(commandUR);
		_Redocommands.Clear();
	}

	/// 
	/// <param name="trening"></param>
	public void InsertInUnDoRedoForDelete(Osoba osoba, IDBService service, Trening trening, out string message)
	{
		message = "";
		ICommandUR commandUR = new DeleteTrening(trening);

		if (osoba.Role == 0)
			message = commandUR.ExecuteA(osoba.ID, service);
		else
			message = commandUR.ExecuteV(osoba.ID, service);

		this.id = osoba.ID;
		this.service = service;
		this.role = osoba.Role;

		_Undocommands.Push(commandUR);
		_Redocommands.Clear();
	}

	public string Redo(){
		string message = "";
		if (_Redocommands.Count != 0)
		{
			ICommandUR commandUR = _Redocommands.Pop();

			if (this.role == 0)
				message = commandUR.ExecuteA(this.id, this.service);
			else
				message = commandUR.ExecuteV(this.id, this.service);

			_Undocommands.Push(commandUR);
		}
		return message != "" ? message : "There are no previous action!";
	}

	public string Undo(){
		string message = "";
		if (_Undocommands.Count != 0)
		{
			ICommandUR commandUR = _Undocommands.Pop();

			if (this.role == 0)
				message = commandUR.UnExecuteA(this.id, this.service);
			else
				message = commandUR.UnExecuteV(this.id, this.service);

			_Redocommands.Push(commandUR);
		}
		return message != "" ? message : "There are no previous action!";
	}

}//end UndoRedo