///////////////////////////////////////////////////////////
//  Vežbac.cs
//  Implementation of the Class Vezbac
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: tanja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Vezbac : Osoba {

	public List<Trening> treninzi;

	public Vezbac(){

	}

	~Vezbac(){

	}

	public override int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

	public override string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	public override int Role{
		get{
			return role;
		}
		set{
			role = value;
		}
	}

	public override string Surname{
		get{
			return surname;
		}
		set{
			surname = value;
		}
	}

	public override string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

}//end Vezbac