///////////////////////////////////////////////////////////
//  Vežbac.cs
//  Implementation of the Class Vezbac
//  Generated by Enterprise Architect
//  Created on:      09-Sep-2020 10:25:33 PM
//  Original author: tanja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Vezbac : Osoba {

	public List<Trening> treninzi;

	public Vezbac(){

	}

	~Vezbac(){

	}

	protected override int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

	protected override string Name{
		get{
			return name;
		}
		set{
			name = value;
		}
	}

	protected override int Role{
		get{
			return role;
		}
		set{
			role = value;
		}
	}

	protected override string Surname{
		get{
			return surname;
		}
		set{
			surname = value;
		}
	}

	protected override string Username{
		get{
			return username;
		}
		set{
			username = value;
		}
	}

	protected override string Password{
		get{
			return password;
		}
		set{
			password = value;
		}
	}

	public override string ToString(){

		return $"{Name} {Surname} [{Username}-{Role}]";
	}

}//end Vezbac